
baseDir = pwd();

addpath(...
    baseDir, ...
    [baseDir '/sensitivity_real'], ...
    [baseDir '/test_academic'], ...
    [baseDir '/test_real'], ...
    [baseDir '/utils'] ...
);

clear('baseDir');