load("test_real/exp_2412_U.mat", "M_released", "dt_mass", "T");
M_reference = M_released;
Ts = 0:dt_mass:T;
%
load("sensitivity_real/beta++.mat", "M_released");
M_betaP = M_released;
load("sensitivity_real/beta+.mat", "M_released");
M_betap = M_released;
%
load("sensitivity_real/Dcoat1++.mat", "M_internal");
M_D1P = M_internal(1, :) - M_internal;
load("sensitivity_real/Dcoat1+.mat", "M_internal");
M_D1p = M_internal(1, :) - M_internal;
load("sensitivity_real/Dcoat1-.mat", "M_released");
M_D1m = M_released;
load("sensitivity_real/Dcoat1--.mat", "M_released");
M_D1M = M_released;
%
load("sensitivity_real/Dcoat2++.mat", "M_released");
M_D2P = M_released;
load("sensitivity_real/Dcoat2+.mat", "M_released");
M_D2p = M_released;
load("sensitivity_real/Dcoat2-.mat", "M_released");
M_D2m = M_released;
load("sensitivity_real/Dcoat2--.mat", "M_released");
M_D2M = M_released;
%
load("sensitivity_real/Dcore++.mat", "M_released");
M_D0P = M_released;
load("sensitivity_real/Dcore+.mat", "M_released");
M_D0p = M_released;
load("sensitivity_real/Dcore-.mat", "M_released");
M_D0m = M_released;
load("sensitivity_real/Dcore--.mat", "M_released");
M_D0M = M_released;
%
load("sensitivity_real/lambdaD.mat", "M_released");
M_lambdaD = M_released;
load("sensitivity_real/lambda+++.mat", "M_released");
M_lambdaP = M_released;
load("sensitivity_real/lambda+.mat", "M_released");
M_lambdap = M_released;
load("sensitivity_real/lambda-.mat", "M_released");
M_lambdam = M_released;
load("sensitivity_real/lambdaN.mat", "M_released");
M_lambdaN = M_released;

clear("M_internal", "M_released")

%%

% scale = 40;
% fig = figure(Position=[0, 0, 21*scale, 7*scale]);
% t = tiledlayout(fig, 'horizontal');
scale = 80;

cP = "#0072BD";
cp = "#4DBEEE";
cr = 'black';
cm = "#D95319";
cM = "#A2142F";
c0 = "#7E2F8E";
cD = "#77AC30";

xmax = 240;
ymax = 425;

%============ 1
fig = figure(Position=[0, 0, 3*scale, 4*scale]);
ax = axes(Parent=fig);
%ax = nexttile(t);

ax.TickLabelInterpreter = 'latex';
hold(ax, 'on')
plp = plot(ax, ...
    Ts/60, cumsum(M_betap(:, 2)), ...
    'Color', cp, ...
    'LineWidth', 2 ...
);
plP = plot(ax, ...
    Ts/60, cumsum(M_betaP(:, 2)), ...
    'Color', cP, ...
    'LineWidth', 2 ...
);
title(ax, "$\beta$ [s$^{-1}$]", Interpreter='latex', FontSize=20)
plr = plot(ax, ...
    Ts/60, cumsum(M_reference(:, 2)), ...
    'Color', cr, ...
    'LineStyle', ':', ...
    'LineWidth', 2 ...
);
hold(ax, 'off');


legend(...
    [plr, plp, plP], ...
    '$0$', ...
    '$1\times10^{-5}$', ...
    '$1\times10^{-4}$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest' ...
    ... 'Location', 'southoutside' ...
);
ylim(ax, [0, ymax])
xlim(ax, [0, xmax])
xlabel(ax, '$t$ [min]', 'Interpreter', 'latex')
ylabel(ax, '$m$ [$\mu$g]', 'Interpreter', 'latex')



exportgraphics(fig, "img/sensitivity_beta.pdf")

%============ 2
fig = figure(Position=[0, 0, 3*scale, 4*scale]);
ax = axes(Parent=fig);
%ax = nexttile(t);

ax.TickLabelInterpreter = 'latex';
hold(ax, 'on')
plN = plot(ax, ...
    Ts/60, cumsum(M_lambdaN(:, 2)), ...
    'Color', cM, ...
    'LineWidth', 2 ...
);
plm = plot(ax, ...
    Ts/60, cumsum(M_lambdam(:, 2)), ...
    'Color', cm, ...
    'LineWidth', 2 ...
);
plp = plot(ax, ...
    Ts/60, cumsum(M_lambdap(:, 2)), ...
    'Color', cp, ...
    'LineWidth', 2 ...
);
plP = plot(ax, ...
    Ts/60, cumsum(M_lambdaP(:, 2)), ...
    'Color', cP, ...
    'LineWidth', 2 ...
);
plD = plot(ax, ...
    Ts/60, cumsum(M_lambdaD(:, 2)), ...
    'Color', cD, ...
    'LineWidth', 2 ...
);
plr = plot(ax, ...
    Ts/60, cumsum(M_reference(:, 2)), ...
    'Color', cr, ...
    'LineStyle', ':', ...
    'LineWidth', 2 ...
);
hold(ax, 'off')
legend(...
    [plN, plm, plr, plp, plP, plD], ...
    '$0.00$ (Neu.0)', ...
    '$0.01$', ...
    '$0.05$', ...
    '$0.25$', ...
    '$1.00$', ...
    '$+\infty$ (Dir.0)', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest' ...
);
title(ax, "$\lambda$ [$\mu$m/s]", Interpreter='latex', FontSize=20)
ylim(ax, [0, ymax])
xlim(ax, [0, xmax])
xlabel(ax, '$t$ [min]', 'Interpreter', 'latex')
% set(ax,'YTickLabel',[]);
ylabel(ax, '$m$ [$\mu$g]', 'Interpreter', 'latex')

exportgraphics(fig, "img/sensitivity_lambda.pdf")

%============ 3

fig = figure(Position=[0, 0, 3*scale, 4*scale]);
ax = axes(Parent=fig);
%ax = nexttile(t);

ax.TickLabelInterpreter = 'latex';
hold(ax, 'on')
plM = plot(ax, ...
    Ts/60, cumsum(M_D0M(:, 2)), ...
    'Color', cM, ...
    'LineWidth', 2 ...
);
plm = plot(ax, ...
    Ts/60, cumsum(M_D0m(:, 2)), ...
    'Color', cm, ...
    'LineWidth', 2 ...
);
plp = plot(ax, ...
    Ts/60, cumsum(M_D0p(:, 2)), ...
    'Color', cp, ...
    'LineWidth', 2 ...
);
plP = plot(ax, ...
    Ts/60, cumsum(M_D0P(:, 2)), ...
    'Color', cP, ...
    'LineWidth', 2 ...
);
plr = plot(ax, ...
    Ts/60, cumsum(M_reference(:, 2)), ...
    'Color', cr, ...
    'LineStyle', ':', ...
    'LineWidth', 2 ...
);
title(ax, "$D^+_{1}$ [$\mu$m$^2$/s]", Interpreter='latex', FontSize=20)
hold(ax, 'off')

legend(...
    [plM, plm, plr, plp, plP], ...
    '$6\times10^{-9}$', ...
    '$6\times10^{-8}$', ...
    '$6\times10^{-7}$', ...
    '$6\times10^{-6}$', ...
    '$6\times10^{-5}$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest' ...
);
ylim(ax, [0, ymax])
xlim(ax, [0, xmax])
xlabel(ax, '$t$ [min]', 'Interpreter', 'latex')
ylabel(ax, '$m$ [$\mu$g]', 'Interpreter', 'latex')



exportgraphics(fig, "img/sensitivity_D1.pdf")

%============ 4

fig = figure(Position=[0, 0, 3*scale, 4*scale]);
ax = axes(Parent=fig);
%ax = nexttile(t);

ax.TickLabelInterpreter = 'latex';
hold(ax, 'on')
plM = plot(ax, ...
    Ts/60, cumsum(M_D1M(:, 2)), ...
    'Color', cM, ...
    'LineWidth', 2 ...
);
plm = plot(ax, ...
    Ts/60, cumsum(M_D1m(:, 2)), ...
    'Color', cm, ...
    'LineWidth', 2 ...
);
plp = plot(ax, ...
    Ts/60, M_D1p(:, 2), ...
    'Color', cp, ...
    'LineWidth', 2 ...
);
plP = plot(ax, ...
    Ts/60, M_D1P(:, 2), ...
    'Color', cP, ...
    'LineWidth', 2 ...
);
plr = plot(ax, ...
    Ts/60, cumsum(M_reference(:, 2)), ...
    'Color', cr, ...
    'LineStyle', ':', ...
    'LineWidth', 2 ...
);
title(ax, "$D^+_{2-3}$ [$\mu$m$^2$/s]", Interpreter='latex', FontSize=20)
hold(ax, 'off')

legend(...
    [plM, plm, plr, plp, plP], ...
    '$5\times10^{-8}$', ...
    '$5\times10^{-7}$', ...
    '$5\times10^{-6}$', ...
    '$5\times10^{-5}$', ...
    '$5\times10^{-4}$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest' ...
);
ylim(ax, [0, ymax])
xlim(ax, [0, xmax])
xlabel(ax, '$t$ [min]', 'Interpreter', 'latex')
ylabel(ax, '$m$ [$\mu$g]', 'Interpreter', 'latex')



exportgraphics(fig, "img/sensitivity_D2.pdf")

%============ 5

fig = figure(Position=[0, 0, 3*scale, 4*scale]);
ax = axes(Parent=fig);
%ax = nexttile(t);

ax.TickLabelInterpreter = 'latex';
hold(ax, 'on')
plM = plot(ax, ...
    Ts/60, cumsum(M_D2M(:, 2)), ...
    'Color', cM, ...
    'LineWidth', 2 ...
);
plm = plot(ax, ...
    Ts/60, cumsum(M_D2m(:, 2)), ...
    'Color', cm, ...
    'LineWidth', 2 ...
);
plp = plot(ax, ...
    Ts/60, cumsum(M_D2p(:, 2)), ...
    'Color', cp, ...
    'LineWidth', 2 ...
);
plP = plot(ax, ...
    Ts/60, cumsum(M_D2P(:, 2)), ...
    'Color', cP, ...
    'LineWidth', 2 ...
);
plr = plot(ax, ...
    Ts/60, cumsum(M_reference(:, 2)), ...
    'Color', cr, ...
    'LineStyle', ':', ...
    'LineWidth', 2 ...
);
title(ax, "$D^+_{4-9}$ [$\mu$m$^2$/s]", Interpreter='latex', FontSize=20)
hold(ax, 'off')

legend(...
    [plM, plm, plr, plp, plP], ...
    '$1\times10^{-8}$', ...
    '$1\times10^{-7}$', ...
    '$1\times10^{-6}$', ...
    '$1\times10^{-5}$', ...
    '$1\times10^{-4}$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest' ...
);


ylim(ax, [0, ymax])
xlim(ax, [0, xmax])
xlabel(ax, '$t$ [min]', 'Interpreter', 'latex')
ylabel(ax, '$m$ [$\mu$g]', 'Interpreter', 'latex')



exportgraphics(fig, "img/sensitivity_D3.pdf")

